# Generated by Django 3.0.4 on 2020-05-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20200527_1013'),
        ('streets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streets',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.City'),
        ),
    ]
