# Generated by Django 3.0.4 on 2020-05-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
    ]
